config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  root to: "homes#top"
  get "home/about" => "homes#about"
  get "search" => "searches#search"
  get "relationships/followings"
  get "relationships/followers"
  get "chat/:id" => "chats#show", as: "chat"
  resources :chats, only: [:create]

  resources :books, only: [:index, :show, :edit, :create, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
    get "favorites" => "favorites#favorites"
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :ensure_correct_user, only: [:favorites]

  def favorites
    @user = User.find(params[:user_id])
    @books = @user.favorites
  end

  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: @book.id)
    favorite.save
    # redirect_to request.referer
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: @book.id)
    favorite.destroy
    # redirect_to request.referer
  end

  private
    def ensure_correct_user
      @user = User.find(params[:user_id])
      if @user.id != current_user.id
        redirect_to user_path(current_user.id), notice: " 「いいねした本一覧」画面は本人以外閲覧できません"
      end
    end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_btn.html.erb
<% if book.favorited_by?(current_user) %>
  <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
    <i class="fas fa-heart" aria-hidden="true" style="color: #dc3545;"></i>
    <span class="text-danger"><%= book.favorites.count %></span>
  <% end %>
<% else %>
  <%= link_to book_favorites_path(book), method: :post, remote: true do %>
    <i class="fas fa-heart" aria-hidden="true"></i>
    <%= book.favorites.count %>
  <% end %>
<% end %>

app/views/favorites/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>name</th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td>
          <%= link_to(book.book.user) do %>
            <%= image_tag book.book.user.get_profile_image, size:'50x50' %>
          <% end %>
        </td>
        <td><%= link_to book.book.user.name, user_path(book.book.user) %></td>

        <td><%=  book.book.title %></td>
        <td><%= book.book.body %></td>
        <td>コメント数: <%= book.book.book_comments.count %></td>
        <td>閲覧数: <%= book.book.view_counts.count %></td>
        <td>Rate：
          <span id="star-rate-<%= book.id %>"></span>
          <script>
            $('#star-rate-<%= book.id %>').raty({
              size: 36,
              starOff: "<%= asset_path('star-off.png') %>",
              starOn: "<%= asset_path('star-on.png') %>",
              starHalf: "<%= asset_path('star-half.png') %>",
              half: true,
              readOnly: true,
              score: <%= book.book.rate %>,
            });
          </script>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/favorites/_list-btn.html.erb
<div class="text-center mt-2">
  <% if current_user == user %>
    <%= link_to "いいねした本一覧", user_favorites_path(user.id), class: "btn btn-info d-flex justify-content-center" %>
  <% end %>
</div>

app/views/favorites/create.js.erb
$(".favorite-btn_<%= @book.id %>").html("<%= escape_javascript(render partial: 'favorites/btn', locals: {book: @book}) %>");

app/views/favorites/destroy.js.erb
$(".favorite-btn_<%= @book.id %>").html("<%= escape_javascript(render partial: 'favorites/btn', locals: {book: @book}) %>");

app/views/favorites/favorites.html.erb
<div class="container col-8">
  <h3>Favorites Books</h3>
  <%= render "index", books: @books %>
</div>